package gt.municipalidad.qrds.config;

import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.DataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

/**
 * Ajusta el esquema H2 de pruebas antes de Hibernate. En PostgreSQL no ejecuta SQL:
 * el esquema lo mantiene Hibernate con ddl-auto=update.
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class UsuariosSchemaPatch implements BeanPostProcessor {

    private static final Logger log = LoggerFactory.getLogger(UsuariosSchemaPatch.class);

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) {
        if (bean instanceof DataSource dataSource) {
            parchear(dataSource);
        }
        return bean;
    }

    private void parchear(DataSource dataSource) {
        try (var connection = dataSource.getConnection()) {
            String producto = connection.getMetaData().getDatabaseProductName();
            if (producto == null || !producto.toLowerCase().contains("h2")) {
                return;
            }
            try (var statement = connection.createStatement()) {
                aplicar(statement);
            }
        } catch (Exception ex) {
            log.warn("Parche de esquema omitido: {}", ex.getMessage());
        }
    }

    private void aplicar(Statement statement) throws SQLException {
        statement.execute(
                    "ALTER TABLE IF EXISTS usuarios ADD COLUMN IF NOT EXISTS telefono VARCHAR(20)");
            statement.execute(
                    "ALTER TABLE IF EXISTS usuarios ADD COLUMN IF NOT EXISTS dpi VARCHAR(13)");
            statement.execute(
                    "ALTER TABLE IF EXISTS usuarios ADD COLUMN IF NOT EXISTS acepta_privacidad BOOLEAN DEFAULT FALSE NOT NULL");
            statement.execute(
                    "ALTER TABLE IF EXISTS usuarios ADD COLUMN IF NOT EXISTS email_verificado BOOLEAN DEFAULT FALSE NOT NULL");
            statement.execute("ALTER TABLE IF EXISTS usuarios ALTER COLUMN rol SET DATA TYPE VARCHAR(20)");
            statement.execute(
                    "ALTER TABLE IF EXISTS bitacora_accesos ALTER COLUMN tipo_evento SET DATA TYPE VARCHAR(30)");
            statement.execute(
                    "ALTER TABLE IF EXISTS bitacora_casos ALTER COLUMN tipo_evento SET DATA TYPE VARCHAR(40)");
            statement.execute("ALTER TABLE IF EXISTS casos ALTER COLUMN estado SET DATA TYPE VARCHAR(20)");
            statement.execute("ALTER TABLE IF EXISTS casos ALTER COLUMN prioridad SET DATA TYPE VARCHAR(10)");
            statement.execute("ALTER TABLE IF EXISTS casos ALTER COLUMN tipo_caso SET DATA TYPE VARCHAR(1)");
            statement.execute(
                    "ALTER TABLE IF EXISTS correlativos_caso ALTER COLUMN tipo_caso SET DATA TYPE VARCHAR(1)");
            statement.execute(
                    "ALTER TABLE IF EXISTS documentos_caso ALTER COLUMN origen SET DATA TYPE VARCHAR(20)");
            statement.execute(
                    "ALTER TABLE IF EXISTS seguimientos_caso ALTER COLUMN tipo SET DATA TYPE VARCHAR(20)");
            statement.execute(
                    "ALTER TABLE IF EXISTS casos ADD COLUMN IF NOT EXISTS fecha_resolucion TIMESTAMP WITH TIME ZONE");
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS resoluciones_caso (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        caso_id BIGINT NOT NULL,
                        usuario_id BIGINT NOT NULL,
                        comentario TEXT NOT NULL,
                        tipo_resultado VARCHAR(40) NOT NULL,
                        vigente BOOLEAN DEFAULT TRUE NOT NULL,
                        notificado BOOLEAN DEFAULT FALSE NOT NULL,
                        estado_notificacion VARCHAR(20) NOT NULL,
                        archivo_ruta VARCHAR(500),
                        creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
                        ip_registro VARCHAR(45),
                        CONSTRAINT fk_resolucion_caso FOREIGN KEY (caso_id) REFERENCES casos(id),
                        CONSTRAINT fk_resolucion_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
                    )
                    """);
    }
}
