spring.application.name=qrds-backend
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/qrdsdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-stacktrace=never
server.error.include-message=never

qrds.cors.origins=http://localhost:5173
qrds.portal.mantenimiento=false

qrds.jwt.secret=qrds-municipal-clave-hs256-desarrollo-cambiar-en-produccion-2026
qrds.jwt.expiration-hours=8

qrds.login.max-intentos=5
qrds.login.bloqueo-minutos=15
qrds.login.rate-limit-por-minuto=10

qrds.registro.rate-limit=5
qrds.registro.ventana-minutos=10
qrds.consulta.rate-limit-por-minuto=30
qrds.archivos.directorio=./data/documentos

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=26MB
